/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MenuList: typeof import('./components/MenuList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsView: typeof import('./components/TabsView/index.vue')['default']
    ThemeSettings: typeof import('./components/ThemeSettings/index.vue')['default']
  }
}
